-- Active: 1698341343293@@127.0.0.1@3306
CREATE TABLE videos (
    id TEXT PRIMARY KEY UNIQUE NOT NULL,
    titulo TEXT NOT NULL,
    duracao INTEGER NOT NULL,
    data_upload TEXT DEFAULT (DATETIME()) NOT NULL
);

SELECT * FROM videos;